# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="udemymod"
version="${file.jarVersion}"
displayName="UdemyMod"
credits="Me, myself and I... well maybe also Kaupenjoe"
authors="Segalu"
description='''
Example mod that uses Kotlin for Forge adapted to Udemy Course by Kaupenjoe.
'''
[[dependencies.udemymod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.udemymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
